Prepare future inclusion of Thread CCM nodes ; Improved node build system ; Make-pretty for all code types  (#165)
* [pylibs] Add CCM-commissioning unit test; with Commissioning unit test to include multi-hop commissioning.
* [pylibs] test  to include normal and CCM joiner in one test.
* [ot-rfsim] fixed filter on outgoing (off mesh) packets
* [ot-rfsim] fix build for FTD
* [event] bugfix in event data len; tests added.
* [pylibs][script] aiocoap install for unit-tests only
* [dispatcher][pylibs] added HostEvents counter
* [pcap] insert a dummy 802.15.4 frame at start of every PCAP file, to create a t=0 simulation time reference. This allows any PCAP entry to be associated to a corresponding radio (trace) log entry with exact (to the microsecond) precision.
* [pylibs] added further comments in partial_dataset case study.
* [pcap] fix unit test, related to introduction of t=0 time-reference frame.
* [ot-rfsim] fix macos build error (due to warn)
* [ot-rfsim] add C lang definitions for macOS build cpp in ot-rfsim project.
* [ot-rfsim] adding 'a' in front of function call parameters; and minor format fixes in C code; adding comments; removing FIXME items.
* [pylibs] added more documentation to test_sim_hosts and fixed testing-for-coaps in one test.
* [ot-rfsim] fix build for v1.1, v1.2 for using ot....() platform logging functions.
* [pylibs] fixes to test_commissioning - test sometimes failed.
* [pylibs] narrow test topology to avoid spurious test fails.
* [pylibs] Added  CCM unit test for one CCM joiner
* [ot-rfsim][cli] add version 'ccm' to place CCM nodes; adding branch pr-ccm repo of openthread for building CCM nodes; .gitignore cleanup.
* [script] add make-pretty exclusion for new submodule
* [ccm] added OT Registrar use in unit tests.
* [ot-rfsim] change ccm build script style to match latest 'main' branch merged.
* bumped openthread  to latest code; build and API updates
* [ot-rfsim] radio: compile-fix for otMacFrameGetSequence function signature change.
* [ot-rfsim] script: build only needed targets; store all build results under ./build; introduced main() in all build scripts; separate build dirs for BR/non-BR builds.
* [pylibs] 'joiner startccm' command added.
* [.golangci.yml] new syntax to replace deprecated one
* [.gitmodules] add commented OT CCM submodule (for future)
* [.github][script] updated make-pretty script to support all languages and checks; removed check-pretty.
* [ot-rfsim] improved build system, can now build/update all nodes quickly
* [script] make-pretty script updated; added clang config files from OpenThread.

diff --git a/ot-rfsim/script/build_all b/ot-rfsim/script/build_all
--- a/ot-rfsim/script/build_all
+++ b/ot-rfsim/script/build_all
@@ -27,9 +27,15 @@
 #  POSSIBILITY OF SUCH DAMAGE.
 #
 
-printf "\n./script/build_all  --  builds only OT node versions for which executables are not found.\n\n"
+printf "\n./script/build_all  --  builds all OT node versions (that weren't built yet or require an update)\n\n"
 
 set -euo pipefail
+
+build_error()
+{
+  printf '\n****************\n  Failed build script: %s - stopping.\n****************\n\n' "$@"
+  exit 1
+}
 
 main()
 {
@@ -38,19 +44,16 @@ main()
 
     for VER in v11 v12 v13 latest br; do
         SCRIPTNAME="./script/build_$VER"
-        FTDNAME="./ot-versions/ot-cli-ftd_$VER"
-        if [ "$VER" == "latest" ]; then
-            FTDNAME="./ot-versions/ot-cli-ftd"
-        fi
 
-        if [ -f $FTDNAME ]; then
-            printf '\n%s: file %s is present, skipping this version build.\n\n' "${VER}" "${FTDNAME}"
+        printf 'Node %s: building with script %s\n' "${VER}" "${SCRIPTNAME}"
+        if ${SCRIPTNAME} "${options[@]}" ; then
+          printf 'Node %s: completed build with script %s\n' "${VER}" "${SCRIPTNAME}"
         else
-            printf '%s: building %s' "${VER}" "${FTDNAME}"
-            ${SCRIPTNAME} "${options[@]}" || printf \
-                '\n********************\n  Failed build script: %s - skipping.\n********************\n\n' "${SCRIPTNAME}"
+          build_error "${SCRIPTNAME}"
         fi
     done
+
+    printf '\nSuccessfully completed building all OT node versions.\n'
 }
 
 main "$@"
