[all] support for OT Posix nodes with RCP using realtime UART
This adds support for running a standard OT Posix node in a realtime simulation, where
the Posix process performs realtime SPINEL/HDLC UART communication with an RCP.
Support for RCPs is the basis to for upcoming features like including real OTBRs in a
simulation, either running on the local host or running in a Docker.

The dispatcher/simulation core is updated to allow handling of both 'realtime UART'
(stdout) based CLI and logging interactions and 'virtual-time UART' interactions by
nodes in the same simulation. The real-time simulation mode adapts the simulation
speed slightly, around speed=~1, to keep the time drift w.r.t. the system clock
near 0.

A method `waitForSimulation()` is introduced to avoid the need for custom simulation
event processing loops at different places in the code. Also, the queueing and
filtering of UART/log output of OT nodes is simplified to make the code better
readable and the data flow easier to understand and debug.

The CLI (over PTY/UART/...) echo behavior differs for Linux Posix nodes that are
controlled via stdin/stdout: there is no 'echo' behavior. Depending on OS, there could
be. To handle all possible combinations of platform/node-type, there is a function
'setupCli' added that autodetects whether echo is used for a node, or not, and whether
the CLI connection is functional.
To achieve this feature, some stale/unnecessary code related to the 'assurePrompt()'
function was removed, also making the node CLI code more maintainable.

The 'openthread' submodule is bumped to the latest version to get some required OT
new features in.

Co-authored-by: François Michel <francoismichel.dev@gmail.com>

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -82,7 +82,7 @@ install_package git --apt git --brew git || true
 git submodule update --init --recursive
 
 # Do the rest via the test script, automatically
-./script/test py-ver-unittests || die "OTNS Installation/tests failed!"
+./script/test py-quick-test || die "OTNS Installation/tests failed!"
 
 # Check if 'otns' command is available.
 if [[ -n $(which otns) ]]; then
