fix for shell pretty

diff --git a/script/check-pretty b/script/check-pretty
--- a/script/check-pretty
+++ b/script/check-pretty
@@ -25,15 +25,50 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-. $(dirname $0)/common.sh
+# shellcheck source=script/common.sh
+. "$(dirname "$0")"/common.sh
 
-lint() {
-  if ! installed golangci-lint; then
-    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
-  fi
-  cd $OTNSDIR
-  golangci-lint run "${GOLINT_ARGS[@]}" || die "check pretty failed"
-  echo "Congratulations! Your Go code is pretty."
+do_go_check()
+{
+    echo -e '====================='
+    echo -e '     check Go'
+    echo -e '====================='
+
+    if ! installed golangci-lint; then
+        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)"/bin v1.23.6
+    fi
+    cd "$OTNSDIR"
+    golangci-lint run "${GOLINT_ARGS[@]}" || die "check pretty failed"
+    echo "Congratulations! Your Go code is pretty."
 }
 
-lint
+do_shell_check()
+{
+    echo -e '====================='
+    echo -e '     check shell'
+    echo -e '====================='
+
+    shfmt -f . | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n10 -P"$OTNS_BUILD_JOBS" shfmt -i 4 -bn -ci -fn -s -d
+
+    shfmt -f . | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n10 -P"$OTNS_BUILD_JOBS" shellcheck -x
+}
+
+main()
+{
+    if [ $# == 0 ]; then
+        do_go_check
+        do_shell_check
+    elif [ "$1" == 'go' ]; then
+        do_go_check
+    elif [ "$1" == 'shell' ]; then
+        do_shell_check
+    else
+        echo >&2 "Unsupported check: $1. Supported: go, shell"
+        # 128 for Invalid arguments
+        exit 128
+    fi
+}
+
+main "$@"
diff --git a/script/setup-dev b/script/setup-dev
--- a/script/setup-dev
+++ b/script/setup-dev
@@ -27,66 +27,72 @@
 #
 # This script setup environment for OTNS development.
 
-. $(dirname $0)/common.sh
+# shellcheck source=script/common.sh
+. "$(dirname "$0")"/common.sh
 
-function install_protoc() {
-  local protoc_download_url
+function install_protoc()
+{
+    local protoc_download_url
 
-  if installed protoc; then
-    return 0
-  fi
+    if installed protoc; then
+        return 0
+    fi
 
-  if [[ $Darwin == 1 ]]; then
-    protoc_download_url=https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/protoc-3.11.3-osx-x86_64.zip
-  else
-    protoc_download_url=https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/protoc-3.11.3-linux-x86_64.zip
-  fi
+    if [[ $Darwin == 1 ]]; then
+        protoc_download_url=https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/protoc-3.11.3-osx-x86_64.zip
+    else
+        protoc_download_url=https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/protoc-3.11.3-linux-x86_64.zip
+    fi
 
-  wget $protoc_download_url -O /tmp/protoc.zip
+    wget $protoc_download_url -O /tmp/protoc.zip
 
-  cd /usr/local
-  sudo unzip /tmp/protoc.zip
-  sudo chmod a+x /usr/local/bin/protoc
-  sudo rm -rf protoc.zip
+    cd /usr/local || return 1
+    sudo unzip /tmp/protoc.zip
+    sudo chmod a+x /usr/local/bin/protoc
+    sudo rm -rf protoc.zip
 
-  installed protoc || die "protoc-gen-go not found, make sure /usr/local/bin is included in $PATH"
+    installed protoc || die "protoc-gen-go not found, make sure /usr/local/bin is included in $PATH"
 }
 
-install_protoc_gen_go() {
-  if installed protoc-gen-go; then
-    return 0
-  fi
+install_protoc_gen_go()
+{
+    if installed protoc-gen-go; then
+        return 0
+    fi
 
-  go get -u github.com/golang/protobuf/protoc-gen-go
-  installed protoc-gen-go || die "protoc-gen-go not found, make sure $GOPATH/bin is included in $PATH"
+    go get -u github.com/golang/protobuf/protoc-gen-go
+    installed protoc-gen-go || die "protoc-gen-go not found, make sure $GOPATH/bin is included in $PATH"
 }
 
-install_protoc_gen_grpc_web() {
-  if installed protoc-gen-grpc-web; then
-    return 0
-  fi
+install_protoc_gen_grpc_web()
+{
+    if installed protoc-gen-grpc-web; then
+        return 0
+    fi
 
-  local download_url
+    local download_url
 
-  if [[ $Darwin == 1 ]]; then
-    download_url=https://github.com/grpc/grpc-web/releases/download/1.0.7/protoc-gen-grpc-web-1.0.7-darwin-x86_64
-  else
-    download_url=https://github.com/grpc/grpc-web/releases/download/1.0.7/protoc-gen-grpc-web-1.0.7-linux-x86_64
-  fi
+    if [[ $Darwin == 1 ]]; then
+        download_url=https://github.com/grpc/grpc-web/releases/download/1.0.7/protoc-gen-grpc-web-1.0.7-darwin-x86_64
+    else
+        download_url=https://github.com/grpc/grpc-web/releases/download/1.0.7/protoc-gen-grpc-web-1.0.7-linux-x86_64
+    fi
 
-  wget $download_url -O /tmp/protoc-gen-grpc-web
-  sudo mv /tmp/protoc-gen-grpc-web /usr/local/bin/protoc-gen-grpc-web
-  sudo chmod a+x /usr/local/bin/protoc-gen-grpc-web
+    wget $download_url -O /tmp/protoc-gen-grpc-web
+    sudo mv /tmp/protoc-gen-grpc-web /usr/local/bin/protoc-gen-grpc-web
+    sudo chmod a+x /usr/local/bin/protoc-gen-grpc-web
 
-  installed protoc-gen-grpc-web || die "protoc-gen-grpc-web not found, make sure /usr/local/bin is included in $PATH"
+    installed protoc-gen-grpc-web || die "protoc-gen-grpc-web not found, make sure /usr/local/bin is included in $PATH"
 }
 
-install_nodejs() {
-  sudo apt-get install nodejs npm -y
+install_nodejs()
+{
+    sudo apt-get install nodejs npm -y
 }
 
-install_go_bindata() {
-  go get -u github.com/jteeuwen/go-bindata/...
+install_go_bindata()
+{
+    go get -u github.com/jteeuwen/go-bindata/...
 }
 
 install_protoc
