install wget in install-deps

diff --git a/script/install-deps b/script/install-deps
--- a/script/install-deps
+++ b/script/install-deps
@@ -29,6 +29,38 @@
 
 . "$(dirname $0)"/common.sh
 
+set -e
+
+apt_update_once=0
+
+install_package() {
+  local cmd=$1
+  local apt_pkg=$2
+  local brew_pkg=$3
+
+  # install if command not available
+  if installed "$cmd"; then
+    return 0
+  fi
+
+  if installed apt-get; then
+    if [ "$apt_update_once" -eq "0" ]; then
+      sudo apt-get update || die "apt-get update failed"
+      apt_update_once=1
+    fi
+
+    sudo apt-get install -y --no-install-recommends "$apt_pkg"
+  elif installed brew; then
+    brew install "$brew_pkg"
+  else
+    die "Can not install $cmd on your system, please retry after installing $cmd."
+  fi
+}
+
+install_packages() {
+  install_package wget wget wget
+}
+
 install_grpcwebproxy() {
   if ! installed grpcwebproxy; then
     if [[ $Darwin == 1 ]]; then
@@ -48,6 +80,7 @@ install_python_libs() {
 }
 
 main() {
+    install_packages
     install_grpcwebproxy
     install_python_libs
 }
