[script] install nodes in ~/.local/share/otns so that OTNS can run from anywhere
The installation is updated to copy node executables to a .local/share directory. This directory
is added to the node search path, so that standard OT node executables can be found from any
directory location where OTNS is run from. The build and copying of node executables is added to
the './script/install' script.

Close #587

diff --git a/script/install-otns b/script/install-otns
--- a/script/install-otns
+++ b/script/install-otns
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2020-2026, The OTNS Authors.
 # All rights reserved.
 #
@@ -24,40 +25,31 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-name: Lint
+# Installs OTNS (without any OT node executables) and pyOTNS.
 
-on:
-  push:
-    branches-ignore:
-      - 'dependabot/**'
-  pull_request:
-    branches:
-      - 'main'
+# shellcheck source=script/common.sh
+. "$(dirname "$0")"/common.sh
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number || (github.repository == 'openthread/ot-ns' && github.run_id) || github.ref }}
-  cancel-in-progress: true
+install_otns()
+{
+    go mod tidy
+    repeat 3 go_install ./cmd/...
+    echo "otns installed: $(command -v otns)"
+}
 
-permissions:
-  contents: read
+install_pyotns()
+{
+    activate_python_venv
+    cd pylibs || die "required directory 'pylibs' not found"
+    python3 -m pip install .
+    # python3 setup.py install --user --prefix= 2>/dev/null  #  alternative - fails on macos-14
+    cd - || die "cd failed"
+}
 
-jobs:
-  go-lint:
-    name: Go/Shell/Python/C/Markdown Lint
-    runs-on: ubuntu-24.04
-    env:
-      HOMEBREW_NO_AUTO_UPDATE: 1
-    steps:
-      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
-      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
-        with:
-          go-version: '1.23'
-      - name: Bootstrap
-        run: |
-          sudo apt-get update
-          sudo apt-get --no-install-recommends install -y clang-format-19 clang-tidy-19
-      - name: Check pretty
-        run: |
-          ./script/install-deps
-          ./script/install-otns
-          ./script/make-pretty check
+main()
+{
+    install_pyotns
+    install_otns
+}
+
+main
