Prepare future inclusion of Thread CCM nodes ; Improved node build system ; Make-pretty for all code types  (#165)
* [pylibs] Add CCM-commissioning unit test; with Commissioning unit test to include multi-hop commissioning.
* [pylibs] test  to include normal and CCM joiner in one test.
* [ot-rfsim] fixed filter on outgoing (off mesh) packets
* [ot-rfsim] fix build for FTD
* [event] bugfix in event data len; tests added.
* [pylibs][script] aiocoap install for unit-tests only
* [dispatcher][pylibs] added HostEvents counter
* [pcap] insert a dummy 802.15.4 frame at start of every PCAP file, to create a t=0 simulation time reference. This allows any PCAP entry to be associated to a corresponding radio (trace) log entry with exact (to the microsecond) precision.
* [pylibs] added further comments in partial_dataset case study.
* [pcap] fix unit test, related to introduction of t=0 time-reference frame.
* [ot-rfsim] fix macos build error (due to warn)
* [ot-rfsim] add C lang definitions for macOS build cpp in ot-rfsim project.
* [ot-rfsim] adding 'a' in front of function call parameters; and minor format fixes in C code; adding comments; removing FIXME items.
* [pylibs] added more documentation to test_sim_hosts and fixed testing-for-coaps in one test.
* [ot-rfsim] fix build for v1.1, v1.2 for using ot....() platform logging functions.
* [pylibs] fixes to test_commissioning - test sometimes failed.
* [pylibs] narrow test topology to avoid spurious test fails.
* [pylibs] Added  CCM unit test for one CCM joiner
* [ot-rfsim][cli] add version 'ccm' to place CCM nodes; adding branch pr-ccm repo of openthread for building CCM nodes; .gitignore cleanup.
* [script] add make-pretty exclusion for new submodule
* [ccm] added OT Registrar use in unit tests.
* [ot-rfsim] change ccm build script style to match latest 'main' branch merged.
* bumped openthread  to latest code; build and API updates
* [ot-rfsim] radio: compile-fix for otMacFrameGetSequence function signature change.
* [ot-rfsim] script: build only needed targets; store all build results under ./build; introduced main() in all build scripts; separate build dirs for BR/non-BR builds.
* [pylibs] 'joiner startccm' command added.
* [.golangci.yml] new syntax to replace deprecated one
* [.gitmodules] add commented OT CCM submodule (for future)
* [.github][script] updated make-pretty script to support all languages and checks; removed check-pretty.
* [ot-rfsim] improved build system, can now build/update all nodes quickly
* [script] make-pretty script updated; added clang config files from OpenThread.

diff --git a/script/make-pretty b/script/make-pretty
--- a/script/make-pretty
+++ b/script/make-pretty
@@ -1,35 +1,36 @@
 #!/bin/bash
-# Copyright (c) 2020, The OTNS Authors.
-# All rights reserved.
 #
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are met:
-# 1. Redistributions of source code must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-# 2. Redistributions in binary form must reproduce the above copyright
-#    notice, this list of conditions and the following disclaimer in the
-#    documentation and/or other materials provided with the distribution.
-# 3. Neither the name of the copyright holder nor the
-#    names of its contributors may be used to endorse or promote products
-#    derived from this software without specific prior written permission.
+#  Copyright (c) 2019-2024, The OpenThread Authors.
+#  All rights reserved.
 #
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
-# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
-# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
-# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
-# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
-# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
-# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
-# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
-# POSSIBILITY OF SUCH DAMAGE.
+#  Redistribution and use in source and binary forms, with or without
+#  modification, are permitted provided that the following conditions are met:
+#  1. Redistributions of source code must retain the above copyright
+#     notice, this list of conditions and the following disclaimer.
+#  2. Redistributions in binary form must reproduce the above copyright
+#     notice, this list of conditions and the following disclaimer in the
+#     documentation and/or other materials provided with the distribution.
+#  3. Neither the name of the copyright holder nor the
+#     names of its contributors may be used to endorse or promote products
+#     derived from this software without specific prior written permission.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
+#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
+#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
+#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
+#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+#  POSSIBILITY OF SUCH DAMAGE.
 #
 
 #
-# The script to format source code of OTNS.
+# The script to check or format source code of OTNS.
 #
-# Format all:
+# Format go, c/c++, markdown, python, and shell:
 #
 #     script/make-pretty
 #
@@ -37,14 +38,48 @@
 #
 #     script/make-pretty go
 #
-# Format go.mod only:
+# Format c/c++ only:
 #
-#     script/make-pretty go.mod
+#     script/make-pretty clang
+#     script/make-pretty clang-format
+#     script/make-pretty clang-tidy
+#
+# Format markdown only:
+#
+#     script/make-pretty markdown
+#
+# Format python only:
+#
+#     script/make-pretty python
 #
 # Format shell only:
 #
 #     script/make-pretty shell
 #
+# Check only:
+#
+#     script/make-pretty check go
+#     script/make-pretty check clang
+#     script/make-pretty check clang-format
+#     script/make-pretty check clang-tidy
+#     script/make-pretty check markdown
+#     script/make-pretty check python
+#     script/make-pretty check shell
+#
+
+set -euo pipefail
+
+OT_CLANG_SOURCES=('*.c' '*.cc' '*.cpp' '*.h' '*.hpp')
+readonly OT_CLANG_SOURCES
+
+OT_MARKDOWN_SOURCES=('*.md')
+readonly OT_MARKDOWN_SOURCES
+
+OT_PYTHON_SOURCES=('*.py')
+readonly OT_PYTHON_SOURCES
+
+OT_CLANG_TIDY_FIX_DIRS=('ot-rfsim/src')
+readonly OT_CLANG_TIDY_FIX_DIRS
 
 # shellcheck source=script/common.sh
 . "$(dirname "$0")"/common.sh
@@ -59,6 +94,27 @@ do_go_format()
     golangci-lint run "${GOLINT_ARGS[@]}" --fix || die "make pretty failed"
 }
 
+do_go_format_check()
+{
+    echo -e '====================='
+    echo -e '     check Go'
+    echo -e '====================='
+
+    cd "$OTNSDIR" || return 1
+    golangci-lint run "${GOLINT_ARGS[@]}" || die "make pretty failed"
+}
+
+do_go_mod_check()
+{
+    echo -e '====================='
+    echo -e '     check go.mod'
+    echo -e '====================='
+
+    cp go.mod go.mod.orig
+    go mod tidy
+    diff go.mod go.mod.orig || die "go.mod is not tidy"
+}
+
 do_go_mod_format()
 {
     echo -e '====================='
@@ -68,14 +124,148 @@ do_go_mod_format()
     go mod tidy
 }
 
+do_clang_format()
+{
+    get_openthread
+    echo -e '========================================'
+    echo -e '     format c/c++ (clang-format)'
+    echo -e '========================================'
+
+    git ls-files "${OT_CLANG_SOURCES[@]}" | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n3 -P"$OTNS_BUILD_JOBS" openthread/script/clang-format -style=file -i -verbose
+}
+
+do_clang_format_check()
+{
+    get_openthread
+    echo -e '========================================'
+    echo -e '     check c/c++ (clang-format)'
+    echo -e '========================================'
+
+    git ls-files "${OT_CLANG_SOURCES[@]}" | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n3 -P"$OTNS_BUILD_JOBS" openthread/script/clang-format-check
+}
+
+do_clang_tidy_fix()
+{
+    get_openthread
+    echo -e '========================================'
+    echo -e '     format c/c++ (clang-tidy)'
+    echo -e '========================================'
+
+    (cd ./ot-rfsim \
+        && ./script/build_latest \
+        && cd build/latest \
+        && ../../../openthread/script/clang-tidy -j"$OTNS_BUILD_JOBS" "${OT_CLANG_TIDY_FIX_DIRS[@]}" -fix)
+}
+
+do_clang_tidy_check()
+{
+    get_openthread
+    echo -e '========================================'
+    echo -e '     check c/c++ (clang-tidy)'
+    echo -e '========================================'
+
+    (cd ./ot-rfsim \
+        && ./script/build_latest \
+        && cd build/latest \
+        && ../../../openthread/script/clang-tidy -j"$OTNS_BUILD_JOBS" "${OT_CLANG_TIDY_FIX_DIRS[@]}")
+}
+
+do_markdown_format()
+{
+    echo -e '========================================'
+    echo -e '     format markdown'
+    echo -e '========================================'
+
+    git ls-files "${OT_MARKDOWN_SOURCES[@]}" | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n10 -P"$OTNS_BUILD_JOBS" npx prettier@2.0.4 --write
+}
+
+do_markdown_check()
+{
+    echo -e '========================================'
+    echo -e '     check markdown'
+    echo -e '========================================'
+
+    git ls-files "${OT_MARKDOWN_SOURCES[@]}" | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n10 -P"$OTNS_BUILD_JOBS" npx prettier@2.0.4 --check
+}
+
+do_python_format()
+{
+    echo -e '========================================'
+    echo -e '     format python'
+    echo -e '========================================'
+
+    git ls-files "${OT_PYTHON_SOURCES[@]}" | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n10 -P"$OTNS_BUILD_JOBS" python3 -m yapf --verbose --style '{based_on_style: google, column_limit: 119}' -ipr
+}
+
+do_python_check()
+{
+    echo -e '========================================'
+    echo -e '     check python'
+    echo -e '========================================'
+
+    git ls-files "${OT_PYTHON_SOURCES[@]}" | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n10 -P"$OTNS_BUILD_JOBS" python3 -m yapf --verbose --style '{based_on_style: google, column_limit: 119}' -dpr
+}
+
 do_shell_format()
 {
-    echo -e '====================='
+    echo -e '========================================'
     echo -e '     format shell'
-    echo -e '====================='
+    echo -e '========================================'
 
-    shfmt -f . | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+    git ls-files | xargs shfmt -f | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
         | xargs -n10 -P"$OTNS_BUILD_JOBS" shfmt -i 4 -bn -ci -fn -s -w
+}
+
+do_shell_check()
+{
+    echo -e '========================================'
+    echo -e '     check shell'
+    echo -e '========================================'
+
+    git ls-files | xargs shfmt -f | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n10 -P"$OTNS_BUILD_JOBS" shfmt -i 4 -bn -ci -fn -s -d
+
+    git ls-files | xargs shfmt -f | grep -v -E "^($(echo "${OTNS_EXCLUDE_DIRS[@]}" | tr ' ' '|'))" \
+        | xargs -n10 -P"$OTNS_BUILD_JOBS" shellcheck
+}
+
+do_check()
+{
+    if [ $# == 0 ]; then
+        do_go_format_check
+        do_go_mod_check
+        do_clang_format_check
+        do_clang_tidy_check
+        do_markdown_check
+        do_python_check
+        do_shell_check
+    elif [ "$1" == 'go' ]; then
+        do_go_format_check
+        do_go_mod_check
+    elif [ "$1" == 'clang' ]; then
+        do_clang_format_check
+        do_clang_tidy_check
+    elif [ "$1" == 'clang-format' ]; then
+        do_clang_format_check
+    elif [ "$1" == 'clang-tidy' ]; then
+        do_clang_tidy_check
+    elif [ "$1" == 'markdown' ]; then
+        do_markdown_check
+    elif [ "$1" == 'python' ]; then
+        do_python_check
+    elif [ "$1" == 'shell' ]; then
+        do_shell_check
+    else
+        echo >&2 "Unsupported check: $1. Supported: go, clang, clang-format, clang-tidy, markdown, python, shell"
+        # 128 for Invalid arguments
+        exit 128
+    fi
 }
 
 main()
@@ -85,18 +275,36 @@ main()
     if [ $# == 0 ]; then
         do_go_format
         do_go_mod_format
+        do_clang_tidy_fix
+        do_clang_format
+        do_markdown_format
+        do_python_format
         do_shell_format
     elif [ "$1" == 'go' ]; then
         do_go_format
-    elif [ "$1" == 'go.mod' ]; then
         do_go_mod_format
+    elif [ "$1" == 'clang' ]; then
+        do_clang_tidy_fix
+        do_clang_format
+    elif [ "$1" == 'clang-format' ]; then
+        do_clang_format
+    elif [ "$1" == 'clang-tidy' ]; then
+        do_clang_tidy_fix
+    elif [ "$1" == 'markdown' ]; then
+        do_markdown_format
+    elif [ "$1" == 'python' ]; then
+        do_python_format
     elif [ "$1" == 'shell' ]; then
         do_shell_format
+    elif [ "$1" == 'check' ]; then
+        shift
+        do_check "$@"
     else
-        echo >&2 "Unsupported action: $1. Supported: go, go.mod, shell"
+        echo >&2 "Unsupported action: $1. Supported: go, clang, clang-format, clang-tidy, markdown, python, shell, check"
         # 128 for Invalid arguments
         exit 128
     fi
+
 }
 
 main "$@"
