add initial stress tests

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -31,132 +31,145 @@ set -e
 
 OT_DIR=${OT_DIR:-$HOME/src/openthread}
 if [[ $(uname) == "Darwin" ]]; then
-  OTBIN_DIR=$OT_DIR/output/x86_64-apple-darwin/bin
+    OTBIN_DIR=$OT_DIR/output/x86_64-apple-darwin/bin
 else
-  OTBIN_DIR=$OT_DIR/output/x86_64-unknown-linux-gnu/bin
+    OTBIN_DIR=$OT_DIR/output/x86_64-unknown-linux-gnu/bin
 fi
 
 installed() {
-  command -v $1 >/dev/null 2>&1
+    command -v $1 >/dev/null 2>&1
 }
 
 go_tests() {
-  install_deps
-  install
+    install_deps
+    install
 
-  echo "" >coverage.txt
+    echo "" >coverage.txt
 
-  PKG=$(go list ./...)
+    PKG=$(go list ./...)
 
-  for d in $PKG; do
-    go test -race -coverprofile=profile.out -covermode=atomic $d
-    if [ -f profile.out ]; then
-      cat profile.out >>coverage.txt
-      rm profile.out
-    fi
-  done
+    for d in $PKG; do
+        go test -race -coverprofile=profile.out -covermode=atomic $d
+        if [ -f profile.out ]; then
+            cat profile.out >>coverage.txt
+            rm profile.out
+        fi
+    done
 }
 
 install_deps() {
-  ./script/install-deps
+    ./script/install-deps
 }
 
 install() {
-  ./script/install
+    ./script/install
 }
 
 get_openthread() {
-  if ! [[ -x $OT_DIR ]]; then
-    mkdir -p "$(dirname $OT_DIR)"
-    git clone https://github.com/openthread/openthread.git $OT_DIR
-    cd $OT_DIR
-    ./script/bootstrap
-    ./bootstrap
-    cd -
-  fi
+    if ! [[ -x $OT_DIR ]]; then
+        mkdir -p "$(dirname $OT_DIR)"
+        git clone https://github.com/openthread/openthread.git $OT_DIR
+        cd $OT_DIR
+        ./script/bootstrap
+        ./bootstrap
+        cd -
+    fi
 }
 
 build_openthread() {
-  get_openthread
-  cd $OT_DIR
-  make -f $OT_DIR/examples/Makefile-simulation OTNS=1
-  cd -
+    get_openthread
+    cd $OT_DIR
+    make -f $OT_DIR/examples/Makefile-simulation OTNS=1
+    cd -
 }
 
 py_unittests() {
-  install_deps
-  install
-  build_openthread
-  cd $OTBIN_DIR
-  python3 $OTNSDIR/pylibs/unittests/test_basic.py
-  python3 $OTNSDIR/pylibs/unittests/test_ping.py
-  python3 $OTNSDIR/pylibs/unittests/test_commissioning.py
-  cd -
+    install_deps
+    install
+    build_openthread
+    cd $OTBIN_DIR
+    python3 $OTNSDIR/pylibs/unittests/test_basic.py
+    python3 $OTNSDIR/pylibs/unittests/test_ping.py
+    python3 $OTNSDIR/pylibs/unittests/test_commissioning.py
+    cd -
 }
 
 check_py_example() {
-  echo "Checking pyOTNS example: $1 ..."
-  python3 $1 &
-  local pid=$!
-  sleep 10
-  killall otns || true
-  wait $pid || die "Run pyOTNS example failed :$1"
+    echo "Checking pyOTNS example: $1 ..."
+    python3 $1 &
+    local pid=$!
+    sleep 10
+    killall otns || true
+    wait $pid || die "Run pyOTNS example failed :$1"
 }
 
 py_examples() {
-  install_deps
-  install
-  build_openthread
-  cd $OTBIN_DIR
-  check_py_example $OTNSDIR/pylibs/examples/simple.py
-  check_py_example $OTNSDIR/pylibs/examples/ping.py
-  check_py_example $OTNSDIR/pylibs/examples/form_partition.py
-  check_py_example $OTNSDIR/pylibs/examples/farm.py
-  cd -
+    install_deps
+    install
+    build_openthread
+    cd $OTBIN_DIR
+    check_py_example $OTNSDIR/pylibs/examples/simple.py
+    check_py_example $OTNSDIR/pylibs/examples/ping.py
+    check_py_example $OTNSDIR/pylibs/examples/form_partition.py
+    check_py_example $OTNSDIR/pylibs/examples/farm.py
+    cd -
 }
 
 test_signals() {
-  install_deps
-  install
-  build_openthread
-  cd $OTBIN_DIR
-  python3 $OTNSDIR/pylibs/unittests/test_signals.py
-  cd -
+    install_deps
+    install
+    build_openthread
+    cd $OTBIN_DIR
+    python3 $OTNSDIR/pylibs/unittests/test_signals.py
+    cd -
+}
+
+stress_tests() {
+    install_deps
+    install
+    build_openthread
+    cd $OTBIN_DIR
+    python3 $OTNSDIR/pylibs/stress_tests/run_stress_suite.py "$@"
+    cd -
+}
+
+gen_stress_tests_report() {
+    python3 $OTNSDIR/pylibs/stress_tests/gen_stress_tests_report.py
 }
 
 main() {
-  do_go_tests=0
-  do_py_unittests=0
-  do_py_examples=0
-  do_signals=0
-
-  for var in "$@"; do
-    if [[ "$var" == "go-tests" ]]; then
-      do_go_tests=1
-    elif [[ "$var" == "py-unittests" ]]; then
-      do_py_unittests=1
-    elif [[ "$var" == "py-examples" ]]; then
-      do_py_examples=1
-    elif [[ "$var" == "signals" ]]; then
-      do_signals=1
-    fi
-  done
-
-  if [[ "$do_go_tests" == "1" ]]; then
-    go_tests
-  fi
-
-  if [[ "$do_py_unittests" == "1" ]]; then
-    py_unittests
-  fi
-
-  if [[ "$do_py_examples" == "1" ]]; then
-    py_examples
-  fi
-
-  if [[ "$do_signals" == "1" ]]; then
-    test_signals
-  fi
+    while (("$#")); do
+        case "$1" in
+        go-tests)
+            go_tests
+            shift 1
+            ;;
+        py-unittests)
+            py_unittests
+            shift 1
+            ;;
+        py-examples)
+            py_examples
+            shift 1
+            ;;
+        signals)
+            signals
+            shift 1
+            ;;
+        stress-tests)
+            stress_tests $2
+            shift 2
+            ;;
+        gen-stress-tests-report)
+            gen_stress_tests_report
+            shift 1
+            ;;
+        *)
+            echo "Error: Unsupported test $1" >&2
+            return 1
+            ;;
+        esac
+    done
 }
 
 main "$@"
